import {localAPI} from './local-db.js?v=11';
import {validateBackup} from './backup.js?v=11';
import {companyDefaults,freshService,totals,euro,displayDate,docNumber,docTitle,correctionData,supplementCents,validateCompany,validateService} from './core.js?v=11';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],form=$('#service-form'),companyForm=$('#company-form');
let company={...companyDefaults},savedCompany=null,revision=0,service=freshService(),issued=null,pendingIssue=null,onlineReady=false,userKey=null,dirtyCompany=false,installPrompt=null,busy=false,historyOffset=0,correctionSource=null,correctionReason='';
const escape=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function localGet(k){try{return JSON.parse(localStorage.getItem(k));}catch{return null;}}
function localSet(k,v){try{localStorage.setItem(k,JSON.stringify(v));return true;}catch{return false;}}
function toast(message){$('#toast').textContent=message;$('#toast').hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').hidden=true,6500);}
function draftKey(){return `taxi-draft-v1:${new URL('.',import.meta.url).pathname}:${userKey||'offline'}`;}
function saveDraft(){if(!issued&&!localSet(draftKey(),{service,pendingIssue,correctionSource,correctionReason}))$('#sync-status').textContent='El navegador no permite conservar el borrador al cerrar.';}
function collect(form){return Object.fromEntries(new FormData(form));}
function fill(form,data){for(const [k,v]of Object.entries(data))if(form.elements[k])form.elements[k].value=v??'';}
function setTab(tab){$$('[data-tab]').forEach(b=>{const active=b.dataset.tab===tab;b.setAttribute('aria-selected',active);b.tabIndex=active?0:-1;});$('#panel-service').hidden=tab!=='service';$('#panel-company').hidden=tab!=='company';}
$$('[data-tab]').forEach(b=>{b.onclick=()=>setTab(b.dataset.tab);b.onkeydown=e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const next=b.dataset.tab==='service'?'company':'service';setTab(next);$('#tab-'+next).focus();}};});
function setTheme(dark){document.body.classList.toggle('dark',dark);$('#theme-icon').textContent=dark?'☀':'☾';$('#theme').setAttribute('aria-label',dark?'Cambiar a modo claro':'Cambiar a modo oscuro');localSet('taxi-theme',dark?'dark':'light');}
setTheme((localGet('taxi-theme')||(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'))==='dark');$('#theme').onclick=()=>setTheme(!document.body.classList.contains('dark'));
function renderSupplements(){
 const station=service.supplements.find(s=>s.type==='station'),luggage=service.supplements.find(s=>s.type==='luggage');
 $('#supplements').innerHTML='<div class="supplement-card"><label class="supplement-toggle"><input type="checkbox" data-supplement="stationEnabled" '+(station?'checked':'')+'>Salida de estación</label><label class="supplement-price">Importe incluido (€)<input data-supplement="stationAmount" inputmode="decimal" maxlength="12" placeholder="0,00" value="'+escape(station?.amount||'')+'" '+(!station?'disabled':'')+'></label></div>'+
 '<div class="supplement-card"><label class="supplement-toggle"><input type="checkbox" data-supplement="luggageEnabled" '+(luggage?'checked':'')+'>Maletas o bultos</label><div class="fields two"><label>Precio por unidad (€)<input data-supplement="luggageUnit" inputmode="decimal" maxlength="12" placeholder="0,00" value="'+escape(luggage?.unitAmount||'')+'" '+(!luggage?'disabled':'')+'></label><label>Cantidad (máximo 5)<select data-supplement="luggageQuantity" '+(!luggage?'disabled':'')+'>'+[1,2,3,4,5].map(q=>'<option value="'+q+'" '+(q===(luggage?.quantity||1)?'selected':'')+'>'+q+'</option>').join('')+'</select></label></div><p class="field-note" id="luggage-result"></p></div>'+
 service.supplements.map((s,i)=>s.type?'':'<div class="legacy-supplement"><span>Detalle anterior: '+escape(s.label)+' · '+escape(s.amount)+' €</span><button type="button" class="text-button" data-remove="'+i+'">Quitar este detalle</button></div>').join('');
 renderLuggageResult();
}
function renderLuggageResult(){const item=service.supplements.find(s=>s.type==='luggage');let text='Activa este suplemento si está incluido en el total.';if(item){try{text=item.quantity+' × '+euro(supplementCents({...item,quantity:1}))+' = '+euro(supplementCents(item))+' incluidos';}catch{text='Revisa el precio por unidad.';}}$('#luggage-result').textContent=text;}
$('#supplements').onclick=e=>{const button=e.target.closest('[data-remove]');if(!button||issued||pendingIssue)return;service.supplements.splice(Number(button.dataset.remove),1);renderSupplements();saveDraft();render();};
form.oninput=e=>{if(issued||pendingIssue)return;const control=e.target,field=control.dataset.supplement;if(field){const type=field.startsWith('station')?'station':'luggage';let item=service.supplements.find(s=>s.type===type);if(field.endsWith('Enabled')){if(control.checked&&!item)service.supplements.push(type==='station'?{type,label:'Salida de estación',amount:''}:{type,label:'Maletas o bultos',unitAmount:'',quantity:1,amount:''});if(!control.checked)service.supplements=service.supplements.filter(s=>s.type!==type);renderSupplements();}else if(item){if(field==='stationAmount')item.amount=control.value;else if(field==='luggageUnit')item.unitAmount=control.value;else item.quantity=Number(control.value);renderLuggageResult();}}else if(control.name)service[control.name]=control.value;saveDraft();render();};form.onchange=form.oninput;form.onsubmit=e=>e.preventDefault();
$('#correction-reason').oninput=e=>{correctionReason=e.target.value;saveDraft();};
companyForm.oninput=()=>{company={...companyDefaults,...collect(companyForm)};dirtyCompany=true;$('#company-status').textContent='Cambios pendientes de guardar.';render();};
function render(){const d=issued?.data||{company:correctionSource?.data.company||company,service},p=d.company,s=d.service;let t;$('#supplement-error').hidden=true;try{t=totals(s);}catch(e){try{t=totals({...s,supplements:[]});}catch{t={fare:0,supplements:[],total:0,base:0,tax:0,rate:null};}$('#supplement-error').textContent=e.message;$('#supplement-error').hidden=false;}const type=issued?docTitle(issued):correctionSource?(s.kind==='invoice'?'Factura rectificativa':'Recibo corregido'):s.kind==='invoice'?'Factura':'Recibo',num=issued?docNumber(issued):'Pendiente de emitir';$('#number').textContent=issued?docNumber(issued):'Automático al emitir';$('#document-state').textContent=issued?'Emitido':pendingIssue?'Pendiente de confirmar':correctionSource?'Corrección en borrador':'Borrador';$('#total').textContent=euro(t.total);$('#issue').textContent=issued?'Nuevo servicio':pendingIssue?'Reintentar emisión':correctionSource?(s.kind==='invoice'?'Emitir rectificación ✓':'Guardar recibo corregido ✓'):`Emitir ${type.toLowerCase()}  ✓`;$('#issue').disabled=busy;$('#service-fields').disabled=Boolean(issued||pendingIssue);form.elements.kind.disabled=Boolean(issued||pendingIssue||correctionSource);$('#correction-info').hidden=!correctionSource||Boolean(issued);$('#correction-reference').textContent=correctionSource?'Corrige '+docNumber(correctionSource)+'. Se conservará el documento original.':'';$('#correction-reason').disabled=Boolean(pendingIssue||issued||busy);$('#issue').setAttribute('aria-busy',String(busy));$('#service-lock-note').hidden=!issued&&!pendingIssue;$('#service-lock-note').textContent=issued?'Documento emitido. Los datos están cerrados. Para completar o corregir estos datos, pulsa «Editar servicio».':'La emisión está pendiente de confirmar. Pulsa «Reintentar emisión» antes de continuar.';$('#client-hint').textContent=s.kind==='invoice'?'Obligatorio en facturas':'Opcional en recibos';$('#export-actions').hidden=!issued;$('#issued-toolbar').hidden=!issued;$('#issued-toolbar-number').textContent=issued?docNumber(issued):'';$('#preview-note').textContent=issued?'Documento emitido. Puedes descargarlo y compartirlo.':pendingIssue?'La emisión está pendiente de confirmar. Reintenta para recuperar el mismo número.':'Revisa los datos antes de emitir.';
$('#receipt-preview').innerHTML=`<div class="professional-head"><div><div class="paper-logo">${escape(p.title||companyDefaults.title)}</div><div class="paper-vehicle">Licencia nº ${escape(p.license||'—')}<br>Matrícula ${escape(p.plate||'—')}</div></div><div class="professional-badge"><strong>${escape(type)}</strong><span>${escape(num)}</span></div></div><div class="professional-parties"><div><span class="professional-label">EMISOR</span><strong>${escape(p.name||'Nombre del titular')}</strong><div>${p.nif?'NIF/CIF: '+escape(p.nif):'Identificación fiscal'}</div>${p.address?'<div class="professional-muted">'+escape(p.address)+'</div>':''}${p.nick?'<div class="professional-muted">'+escape(p.nick)+'</div>':''}${p.phone||p.email?'<div class="professional-muted">'+escape([p.phone,p.email].filter(Boolean).join(' · '))+'</div>':''}</div>${s.clientName||s.clientNif||s.clientAddress?`<div><span class="professional-label">CLIENTE / EMPRESA</span><strong>${escape(s.clientName||'—')}</strong>${s.clientNif?'<div>NIF/CIF: '+escape(s.clientNif)+'</div>':''}${s.clientAddress?'<div class="professional-muted">'+escape(s.clientAddress)+'</div>':''}</div>`:''}</div><div class="professional-meta"><div><span class="professional-label">FECHA DEL SERVICIO</span><strong>${displayDate(s.date)} · ${escape(s.time)}</strong></div>${issued?`<div><span class="professional-label">FECHA DE EMISIÓN</span><strong>${escape(new Date(issued.created).toLocaleDateString('es-ES'))}</strong></div>`:''}<div><span class="professional-label">FORMA DE PAGO</span><strong>${escape(s.payment)}</strong></div></div>${(d.correction||correctionSource)?correctionMarkup(d.correction||correctionData(correctionSource,correctionReason.trim()||'Motivo pendiente'),t):''}<section class="professional-details"><h3>DETALLES DEL SERVICIO</h3><div class="professional-route"><div><span class="professional-label">ORIGEN</span><strong>${escape(s.origin||'Punto de recogida')}</strong></div><div><span class="professional-label">DESTINO</span><strong>${escape(s.destination||'Punto de llegada')}</strong></div></div><div class="professional-table"><div class="paper-row professional-table-head"><span>CONCEPTO</span><span>IMPORTE</span></div><div class="paper-row"><span>Importe taxímetro</span><span>${euro(t.fare)}</span></div>${t.supplements.map(x=>`<div class="paper-row"><span>${escape(x.label||'Suplemento')}</span><span>${euro(x.amount)}</span></div>`).join('')}<div class="professional-total"><span>Total servicio</span><strong>${euro(t.total)}</strong></div>${t.rate!==null?`<div class="paper-row professional-muted"><span>Base imponible total</span><span>${euro(t.base)}</span></div><div class="paper-row professional-muted"><span>IVA (${t.rate} %, incluido)</span><span>${euro(t.tax)}</span></div>`:''}</div></section>${s.notes?'<div class="professional-notes"><span class="professional-label">OBSERVACIONES</span>'+escape(s.notes)+'</div>':''}<div class="professional-thanks">Gracias por viajar con nosotros.</div>`;}
function correctionLines(meta,amounts){return [
 'Corrige / sustituye: '+meta.reference,
 'Documento original emitido el '+new Date(meta.sourceCreated).toLocaleDateString('es-ES'),
 'Motivo: '+meta.reason,
 'Corrección por sustitución: se muestran los importes completos corregidos.',
 'Original: base '+euro(meta.oldBase)+' · IVA '+euro(meta.oldTax)+' · total '+euro(meta.oldTotal),
 'Variación: base '+euro(amounts.base-meta.oldBase)+' · IVA '+euro(amounts.tax-meta.oldTax)+' · total '+euro(amounts.total-meta.oldTotal)
 ];}
function correctionMarkup(meta,amounts){return '<div class="paper-correction">'+correctionLines(meta,amounts).map(line=>'<div>'+escape(line)+'</div>').join('')+'</div>';}
async function api(path,options={}){return localAPI(path,options);}

async function sync(){try{const data=await api('state');onlineReady=true;const previousUser=userKey;userKey=data.user;localSet('taxi-last-user',userKey);if(!dirtyCompany){savedCompany=data.company;company={...companyDefaults,...(data.company||{})};revision=data.revision;fill(companyForm,company);$('#company-status').textContent=data.company?'Datos guardados en este dispositivo.':'Completa y guarda los datos de tu empresa.';}if(previousUser!==userKey){issued=null;pendingIssue=null;service=freshService();const draft=localGet(draftKey())||localGet('taxi-draft-v1:offline');if(draft?.service){service=draft.service;pendingIssue=draft.pendingIssue||null;}fill(form,service);renderSupplements();}$('#sync-status').textContent=navigator.onLine?'Guardado en este dispositivo':'Sin conexión · guardado en este dispositivo';render();}catch(e){onlineReady=false;$('#sync-status').textContent='No se puede acceder al almacenamiento del navegador';}}
companyForm.onsubmit=async e=>{e.preventDefault();if(busy)return;let data;try{data=validateCompany(collect(companyForm));}catch(e){toast(e.message);return;}$('#save-company').disabled=true;try{const result=await api('company',{method:'PUT',body:JSON.stringify({company:data,revision})});company=result.company;savedCompany=result.company;revision=result.revision;dirtyCompany=false;$('#company-status').textContent='Datos guardados en este dispositivo.';toast('Datos de empresa guardados.');render();}catch(e){toast(e.message);$('#company-status').textContent=e.message;if(e.status===409){const state=await api('state').catch(()=>null);if(state)revision=state.revision;$('#company-status').textContent='Los datos cambiaron en otra pestaña. Revisa tu formulario y pulsa Guardar para aplicar esta versión.';}}finally{$('#save-company').disabled=false;}};
async function issue(){if(issued){newService();return;}if(busy)return;if(!pendingIssue){if(dirtyCompany||!savedCompany){setTab('company');toast('Guarda los datos de tu empresa antes de emitir.');return;}try{validateService(service,correctionSource?.data.company||savedCompany);if(correctionSource)correctionData(correctionSource,correctionReason);}catch(e){setTab('service');toast(e.message);return;}pendingIssue={id:crypto.randomUUID(),service:structuredClone(service),revision,...(correctionSource?{sourceId:correctionSource.id,reason:correctionReason}:{})};saveDraft();}busy=true;render();try{const result=await api('documents',{method:'POST',body:JSON.stringify(pendingIssue)});issued=result.document;pendingIssue=null;correctionSource=null;correctionReason='';service=issued.data.service;localSet(draftKey(),null);toast(`${docNumber(issued)} emitido. Ya puedes descargarlo o compartirlo.`);$('#sync-status').textContent='Documento guardado en este dispositivo';}catch(e){if(e.status&&e.status>=400){pendingIssue=null;saveDraft();if(e.status===409){await sync();toast(correctionSource?e.message:'Los datos de la empresa han cambiado. Revisa la vista previa y vuelve a emitir.');}else toast(e.message);}else{saveDraft();toast('No pudimos confirmar el guardado. Pulsa «Reintentar emisión» para recuperar el mismo documento sin duplicarlo.');}}finally{busy=false;render();}}
$('#issue').onclick=issue;
function newService(){if(pendingIssue){toast('Confirma primero la emisión pendiente para evitar duplicados.');return;}if(!issued&&(service.origin||service.destination||service.fare||service.clientName)&&!confirm('¿Empezar otro servicio? Se descartará este borrador sin emitir.'))return;issued=null;correctionSource=null;correctionReason='';service=freshService();fill(form,service);renderSupplements();saveDraft();render();setTab('service');window.scrollTo({top:0,behavior:'smooth'});sync();}
$('#new-service').onclick=newService;
$('#edit-issued').onclick=async()=>{if(!issued||pendingIssue||busy)return;try{const result=await api('documents/'+issued.id);correctionSource=structuredClone(result.latest);service=structuredClone(correctionSource.data.service);issued=null;pendingIssue=null;correctionReason='';$('#correction-reason').value='';fill(form,service);renderSupplements();saveDraft();render();setTab('service');window.scrollTo({top:0,behavior:'smooth'});toast('Puedes corregir los datos. Indica el motivo antes de guardar.');}catch(e){toast(e.message);}};
$('#edit-issued-top').onclick=()=>$('#edit-issued').click();
function documentText(){const {company:p,service:s}=issued.data,t=totals(s);return [p.title,`Licencia: ${p.license}`,`Matrícula: ${p.plate}`,'',p.name,`NIF/CIF: ${p.nif}`,p.address,p.nick,p.phone,p.email,'',`${docTitle(issued).toUpperCase()} ${docNumber(issued)}`,'',`Fecha del servicio: ${displayDate(s.date)} ${s.time}`,`Fecha de emisión: ${new Date(issued.created).toLocaleDateString('es-ES')}`,`Forma de pago: ${s.payment}`,'',...(issued.data.correction?[...correctionLines(issued.data.correction,t),'']:[]),...(s.clientName||s.clientNif||s.clientAddress?['CLIENTE',s.clientName,s.clientNif?'NIF/CIF: '+s.clientNif:'',s.clientAddress,'']:[]),'DETALLES DEL SERVICIO',`Origen: ${s.origin}`,`Destino: ${s.destination}`,'',`Importe taxímetro: ${euro(t.fare)}`,...t.supplements.map(x=>`${x.label}: ${euro(x.amount)}`),'',`Total servicio: ${euro(t.total)}`,'',...(t.rate!==null?[`Base imponible total: ${euro(t.base)}`,`IVA (${t.rate} %, incluido): ${euro(t.tax)}`]:[]),'',s.notes,'Gracias por viajar con nosotros.'].filter(x=>x!==undefined).join('\n');}
function saveFile(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);}
function exportFilename(extension){return `servicio-taxi-${issued.data.service.date}-${docNumber(issued)}.${extension}`;}
function download(blob,extension){saveFile(blob,exportFilename(extension));}
function pdfBlob(){
 if(!window.jspdf)throw new Error('No se pudo cargar el generador PDF. Puedes usar Imprimir o descargar el texto.');
 const pdf=new window.jspdf.jsPDF({unit:'mm',format:'a4'}),{company:p,service:s}=issued.data,t=totals(s);
 const left=15.5,right=194.5,width=right-left,ink=[32,42,50],muted=[101,113,123],gold=[233,185,48],gray=[245,247,248],edge=[223,228,232];
 const compact=Boolean(issued.data.correction);let y=22;
 function font(size=10,bold=false,color=ink){pdf.setFont('helvetica',bold?'bold':'normal');pdf.setFontSize(size);pdf.setTextColor(...color);}
 function wrap(value,w,size=10,bold=false){font(size,bold);return pdf.splitTextToSize(String(value||''),w);}
 function text(x,top,value,size=10,bold=false,color=ink,align='left'){font(size,bold,color);pdf.text(String(value),x,top,{align});}
 function rule(top,color=edge,thickness=.25){pdf.setDrawColor(...color);pdf.setLineWidth(thickness);pdf.line(left,top,right,top);}
 function box(x,top,w,h,color=gray){pdf.setFillColor(...color);pdf.roundedRect(x,top,w,h,2,2,'F');}
 function ensure(height){if(y+height<=265)return;pdf.addPage();text(left,16,wrap(p.title||companyDefaults.title,130,9,true)[0],9,true);text(right,16,docNumber(issued),9,false,muted,'right');rule(20,gold,.4);y=29;}
 function paragraph(value,x,w,size=10,bold=false,color=ink){const lines=wrap(value,w,size,bold),step=size*.43+1;for(const row of lines){ensure(step);text(x,y,row,size,bold,color);y+=step;}}
 const titleLines=wrap(p.title||companyDefaults.title,112,18,true);
 for(const row of titleLines){text(left,y,row,18,true);y+=8;}
 y+=1;
 for(const value of ['Licencia nº '+p.license,'Matrícula '+p.plate]){for(const row of wrap(value,112,9.5)){text(left,y,row,9.5,false,muted);y+=4.5;}}
 const badgeX=142,badgeWidth=right-badgeX,typeLines=wrap(docTitle(issued).toUpperCase(),badgeWidth-10,8.5,true),badgeHeight=14+typeLines.length*4.3;
 box(badgeX,15.5,badgeWidth,badgeHeight);
 typeLines.forEach((row,i)=>text(badgeX+5,22+i*4.3,row,8.5,true,muted));
 text(badgeX+5,25+typeLines.length*4.3,docNumber(issued),11,true);
 y=Math.max(y,15.5+badgeHeight)+7;rule(y);y+=9;
 const columnWidth=80,clientX=109.5;
 function party(label,name,values,x){let pos=y;text(x,pos,label,8,true,muted);pos+=7;
  for(const row of wrap(name||'—',columnWidth,11,true)){text(x,pos,row,11,true);pos+=5;}
  pos+=1;
  for(const value of values.filter(Boolean)){for(const row of wrap(value,columnWidth,9.5)){text(x,pos,row,9.5,false,value.startsWith('NIF/CIF:')?ink:muted);pos+=4.5;}pos+=1;}
  return pos;
 }
 const companyBottom=party('EMISOR',p.name,['NIF/CIF: '+p.nif,p.address,p.nick,p.phone,p.email],left);
 const clientBottom=s.clientName||s.clientNif||s.clientAddress?party('CLIENTE / EMPRESA',s.clientName,[s.clientNif?'NIF/CIF: '+s.clientNif:'',s.clientAddress],clientX):y;
 y=Math.max(companyBottom,clientBottom)+9;
 ensure(22);box(left,y,width,19);
 const metadata=[['FECHA DEL SERVICIO',displayDate(s.date)+' · '+s.time],['FECHA DE EMISIÓN',new Date(issued.created).toLocaleDateString('es-ES')],['FORMA DE PAGO',s.payment]];
 metadata.forEach(([label,value],i)=>{const x=left+5+i*(width/3);text(x,y+7,label,7,true,muted);text(x,y+14,value,9.5);});y+=compact?23:29;
 if(issued.data.correction){const rows=correctionLines(issued.data.correction,t);ensure(15);text(left,y,'RECTIFICACIÓN / CORRECCIÓN',9,true);y+=6;for(const row of rows)paragraph(row,left,width,8.5,false,muted);y+=compact?3:6;}
 ensure(25);rule(y,gold,.45);y+=8;text(left,y,'DETALLES DEL SERVICIO',10.5,true);y+=compact?9:13;
 const origin=wrap(s.origin,80,10.5),destination=wrap(s.destination,80,10.5),routeHeight=7+Math.max(origin.length,destination.length)*5;
 ensure(routeHeight+6);text(left,y,'ORIGEN',7.5,true,muted);text(clientX,y,'DESTINO',7.5,true,muted);y+=7;
 origin.forEach((row,i)=>text(left,y+i*5,row,10.5));destination.forEach((row,i)=>text(clientX,y+i*5,row,10.5));y+=Math.max(origin.length,destination.length)*5+(compact?6:11);
 ensure(18);text(left,y,'CONCEPTO',7.5,true,muted);text(right,y,'IMPORTE',7.5,true,muted,'right');y+=4;rule(y);y+=compact?6:8;
 function amountRow(label,amount,size=10,color=ink){const rows=wrap(label,width-37,size),height=rows.length*5;ensure(height+4);rows.forEach((row,i)=>text(left,y+i*5,row,size,false,color));text(right,y,euro(amount),size,false,color,'right');y+=height+(compact?3:4);}
 amountRow('Importe taxímetro',t.fare);for(const item of t.supplements)amountRow(item.label||'Suplemento',item.amount);
 ensure(t.rate===null?22:46);box(left,y,width,18);pdf.setFillColor(...gold);pdf.rect(left,y,1.1,18,'F');text(left+5,y+11,'Total servicio',13,true);text(right-5,y+12,euro(t.total),20,true,ink,'right');y+=27;
 if(t.rate!==null){amountRow('Base imponible total',t.base,9.5,muted);amountRow('IVA ('+t.rate+' %, incluido)',t.tax,9.5,muted);}
 if(s.notes){y+=4;ensure(12);text(left,y,'OBSERVACIONES',8,true,muted);y+=6;paragraph(s.notes,left,width,9,false,muted);}
 const pages=pdf.getNumberOfPages();for(let i=1;i<=pages;i++){pdf.setPage(i);rule(274);text(left,283,'Gracias por viajar con nosotros.',8,false,muted);text(left,292,docNumber(issued),7.5,false,muted);text(right,292,i+' / '+pages,7.5,false,muted,'right');}
 return pdf.output('blob');
}
$('#pdf').onclick=()=>{try{download(pdfBlob(),'pdf');}catch(e){toast(e.message);}};$('#text').onclick=()=>download(new Blob(['\ufeff'+documentText()],{type:'text/plain;charset=utf-8'}),'txt');$('#print').onclick=()=>{document.title=exportFilename('pdf').replace(/\.pdf$/,'');window.print();document.title='Taxi · Recibos';};
$('#share').onclick=async()=>{try{const file=new File([pdfBlob()],exportFilename('pdf'),{type:'application/pdf'});if(navigator.canShare?.({files:[file]})){await navigator.share({files:[file],title:docNumber(issued)});}else if(navigator.share){await navigator.share({title:docNumber(issued),text:documentText()});}else{download(file,'pdf');toast('PDF descargado. Puedes adjuntarlo por WhatsApp o email.');}}catch(e){if(e.name!=='AbortError')toast(e.message||'No se pudo compartir. Descarga el PDF para adjuntarlo.');}};
async function showHistory(reset=true){const list=$('#history-list');if(reset){historyOffset=0;list.innerHTML='<p class="empty-state">Cargando documentos…</p>';if(!$('#history-dialog').open)$('#history-dialog').showModal();}try{const data=await api('documents?offset='+historyOffset);if(reset)list.innerHTML='';list.querySelector('.load-more')?.remove();if(!data.documents.length&&!historyOffset)list.innerHTML='<p class="empty-state">Todavía no hay documentos.<br>Tu primer recibo aparecerá aquí al emitirlo.</p>';for(const d of data.documents){const b=document.createElement('button');b.className='history-row';b.innerHTML=`<span><strong>${escape(docNumber(d))}</strong><small>${displayDate(d.data.service.date)} · ${escape(d.data.service.clientName||d.data.service.destination)}</small></span><strong>${euro(totals(d.data.service).total)}</strong>`;b.onclick=()=>{if(pendingIssue){toast('Confirma primero la emisión pendiente.');return;}if(!issued&&(service.origin||service.destination||service.fare)&&!confirm('¿Abrir este documento? Se conservará tu borrador para cuando vuelvas a abrir la app.'))return;issued=d;correctionSource=null;correctionReason='';service=d.data.service;fill(form,service);renderSupplements();render();setTab('service');$('#history-dialog').close();window.scrollTo({top:0,behavior:'smooth'});};list.append(b);}historyOffset+=data.documents.length;if(data.more){const more=document.createElement('button');more.className='button quiet load-more';more.textContent='Cargar más';more.onclick=()=>showHistory(false);list.append(more);}}catch(e){if(reset)list.innerHTML='';const p=document.createElement('p');p.className='empty-state';p.textContent=e.message;list.append(p);const retry=document.createElement('button');retry.className='button quiet';retry.textContent='Reintentar';retry.onclick=()=>showHistory(true);list.append(retry);}}
$('#history-button').onclick=()=>showHistory();$$('[data-close]').forEach(b=>b.onclick=()=>$('#'+b.dataset.close).close());
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;});$('#install').onclick=async()=>{if(installPrompt){await installPrompt.prompt();installPrompt=null;}else $('#install-dialog').showModal();};window.addEventListener('appinstalled',()=>{$('#install').hidden=true;toast('Aplicación instalada.');});if(matchMedia('(display-mode: standalone)').matches)$('#install').textContent='Instalación / ayuda';
userKey='this-device';const draft=localGet(draftKey());if(draft?.service&&Array.isArray(draft.service.supplements)){service={...freshService(),...draft.service};pendingIssue=draft.pendingIssue||null;correctionSource=draft.correctionSource||null;correctionReason=draft.correctionReason||'';}$('#correction-reason').value=correctionReason;fill(form,service);fill(companyForm,company);renderSupplements();render();sync();window.addEventListener('online',sync);window.addEventListener('offline',()=>{$('#sync-status').textContent='Sin conexión · guardado en este dispositivo';onlineReady=false;});document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&!busy)sync();});
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js',{scope:'./',updateViaCache:'none'}).catch(()=>{ $('#sync-status').textContent='El modo sin conexión no está disponible en este navegador.'; });
if(document.modelContext?.registerTool){const controller=new AbortController();try{Promise.resolve(document.modelContext.registerTool({name:'read_taxi_document_draft',title:'Consultar el servicio de taxi',description:'Lee el borrador visible o el documento emitido, sin emitir ni modificar datos.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:input=>{if(!input||Object.keys(input).length)throw new Error('No se admiten parámetros.');return {status:issued?'issued':pendingIssue?'pending':'draft',number:issued?docNumber(issued):null,service:structuredClone(service)};}},{signal:controller.signal})).catch(()=>{});}catch{}window.addEventListener('pagehide',()=>controller.abort(),{once:true});}

$('#backup-export').onclick=async()=>{try{const data=await api('backup');saveFile(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),'taxi-copia-'+new Date().toISOString().slice(0,10)+'.json');$('#backup-status').textContent='Copia descargada: '+data.documents.length+' documentos. Guarda el archivo fuera de este navegador.';toast('Copia JSON descargada. Incluye documentos, empresa y contador.');}catch(e){toast(e.message);}};
$('#backup-import').onclick=()=>$('#backup-file').click();
$('#backup-file').onchange=async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;if(pendingIssue){toast('Confirma primero la emisión pendiente.');return;}try{if(file.size>20*1024*1024)throw new Error('La copia es demasiado grande. Máximo 20 MB.');const text=await file.text();let data;try{data=JSON.parse(text.replace(/^\uFEFF/,''));}catch{throw new Error('El archivo no contiene un JSON válido.');}const checked=validateBackup(data);if(!confirm('¿Importar '+checked.documents.length+' documentos de '+(checked.company?.name||'esta copia')+'? Se conservarán los existentes. Si hay números en conflicto, no se importará nada.'))return;const result=await api('backup',{method:'POST',body:JSON.stringify(data)});dirtyCompany=false;await sync();await showHistory();$('#backup-status').textContent=result.imported+' documentos importados · '+result.skipped+' ya estaban guardados.';toast('Copia importada. El contador se ha actualizado.');}catch(e){toast(e.message);$('#backup-status').textContent=e.message;}};
if(navigator.storage?.persist)navigator.storage.persist().catch(()=>{});
