import {localAPI} from './local-db.js';
import {validateBackup} from './backup.js';
import {companyDefaults,freshService,totals,euro,displayDate,docNumber,validateCompany,validateService} from './core.js';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],form=$('#service-form'),companyForm=$('#company-form');
let company={...companyDefaults},savedCompany=null,revision=0,service=freshService(),issued=null,pendingIssue=null,onlineReady=false,userKey=null,dirtyCompany=false,installPrompt=null,busy=false,historyOffset=0;
const escape=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function localGet(k){try{return JSON.parse(localStorage.getItem(k));}catch{return null;}}
function localSet(k,v){try{localStorage.setItem(k,JSON.stringify(v));return true;}catch{return false;}}
function toast(message){$('#toast').textContent=message;$('#toast').hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').hidden=true,6500);}
function draftKey(){return `taxi-draft-v1:${new URL('.',import.meta.url).pathname}:${userKey||'offline'}`;}
function saveDraft(){if(!issued&&!localSet(draftKey(),{service,pendingIssue}))$('#sync-status').textContent='El navegador no permite conservar el borrador al cerrar.';}
function collect(form){return Object.fromEntries(new FormData(form));}
function fill(form,data){for(const [k,v]of Object.entries(data))if(form.elements[k])form.elements[k].value=v??'';}
function setTab(tab){$$('[data-tab]').forEach(b=>{const active=b.dataset.tab===tab;b.setAttribute('aria-selected',active);b.tabIndex=active?0:-1;});$('#panel-service').hidden=tab!=='service';$('#panel-company').hidden=tab!=='company';}
$$('[data-tab]').forEach(b=>{b.onclick=()=>setTab(b.dataset.tab);b.onkeydown=e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const next=b.dataset.tab==='service'?'company':'service';setTab(next);$('#tab-'+next).focus();}};});
function setTheme(dark){document.body.classList.toggle('dark',dark);$('#theme-icon').textContent=dark?'☀':'☾';$('#theme').setAttribute('aria-label',dark?'Cambiar a modo claro':'Cambiar a modo oscuro');localSet('taxi-theme',dark?'dark':'light');}
setTheme((localGet('taxi-theme')||(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'))==='dark');$('#theme').onclick=()=>setTheme(!document.body.classList.contains('dark'));
function renderSupplements(){ $('#supplements').innerHTML=service.supplements.map((s,i)=>`<div class="supplement"><label>Concepto<input data-supp="${i}" data-key="label" maxlength="100" placeholder="Ej. aeropuerto" value="${escape(s.label)}"></label><label>Importe (€)<input data-supp="${i}" data-key="amount" inputmode="decimal" maxlength="12" placeholder="0,00" value="${escape(s.amount)}"></label><button type="button" class="remove-supplement" data-remove="${i}" aria-label="Eliminar suplemento ${i+1}">×</button></div>`).join('');$('#add-supplement').disabled=service.supplements.length>=12;}
$('#add-supplement').onclick=()=>{if(service.supplements.length>=12)return;service.supplements.push({label:'',amount:''});renderSupplements();saveDraft();render();$('#supplements .supplement:last-child input').focus();};
$('#supplements').onclick=e=>{const b=e.target.closest('[data-remove]');if(b){service.supplements.splice(Number(b.dataset.remove),1);renderSupplements();saveDraft();render();}};
form.oninput=e=>{if(issued||pendingIssue)return;if(e.target.dataset.supp!==undefined)service.supplements[Number(e.target.dataset.supp)][e.target.dataset.key]=e.target.value;else if(e.target.name)service[e.target.name]=e.target.value;saveDraft();render();};form.onchange=form.oninput;form.onsubmit=e=>e.preventDefault();
companyForm.oninput=()=>{company={...companyDefaults,...collect(companyForm)};dirtyCompany=true;$('#company-status').textContent='Cambios pendientes de guardar.';render();};
function render(){const d=issued?.data||{company,service},p=d.company,s=d.service;let t;try{t=totals(s);}catch{t={fare:0,supplements:[],total:0,base:0,tax:0,rate:null};}const type=s.kind==='invoice'?'Factura':'Recibo',num=issued?docNumber(issued):'Pendiente de emitir';$('#number').textContent=issued?docNumber(issued):'Automático al emitir';$('#document-state').textContent=issued?'Emitido':pendingIssue?'Pendiente de confirmar':'Borrador';$('#total').textContent=euro(t.total);$('#issue').textContent=issued?'Nuevo servicio':pendingIssue?'Reintentar emisión':`Emitir ${type.toLowerCase()}  ✓`;$('#issue').disabled=busy;$('#service-fields').disabled=Boolean(issued||pendingIssue);$('#client-hint').textContent=s.kind==='invoice'?'Obligatorio en facturas':'Opcional en recibos';$('#export-actions').hidden=!issued;$('#preview-note').textContent=issued?'Documento emitido. Puedes descargarlo y compartirlo.':pendingIssue?'La emisión está pendiente de confirmar. Reintenta para recuperar el mismo número.':'Revisa los datos antes de emitir.';
$('#receipt-preview').innerHTML=`<div class="paper-head"><div><div class="paper-logo">${escape(p.title||companyDefaults.title)}</div><div class="paper-vehicle">Licencia nº ${escape(p.license||'—')}<br>Matrícula ${escape(p.plate||'—')}</div></div></div><div class="paper-company"><strong>${escape(p.name||'Nombre del titular')}</strong><br>${p.nif?'NIF/CIF: '+escape(p.nif):'<span class="paper-muted">Identificación fiscal</span>'}${p.address?'<br>'+escape(p.address):''}${p.nick?'<br>'+escape(p.nick):''}${p.phone||p.email?'<br><span class="paper-muted">'+escape([p.phone,p.email].filter(Boolean).join(' · '))+'</span>':''}</div><div class="paper-number"><strong>${type}</strong><span>${escape(num)}</span></div><div class="paper-meta"><div><span class="paper-muted">Fecha del servicio</span><strong>${displayDate(s.date)} · ${escape(s.time)}</strong></div><div><span class="paper-muted">Forma de pago</span><strong>${escape(s.payment)}</strong></div></div>${s.clientName||s.clientNif||s.clientAddress?`<div class="paper-client"><span class="paper-muted">CLIENTE</span><br><strong>${escape(s.clientName)}</strong>${s.clientNif?'<br>NIF/CIF: '+escape(s.clientNif):''}${s.clientAddress?'<br>'+escape(s.clientAddress):''}</div>`:''}<div class="paper-route"><div><span>ORIGEN</span>${escape(s.origin||'Punto de recogida')}</div><div><span>DESTINO</span>${escape(s.destination||'Punto de llegada')}</div></div><div class="paper-amounts"><div class="paper-row"><span>Servicio de taxi</span><span>${euro(t.fare)}</span></div>${t.supplements.map(x=>`<div class="paper-row"><span>${escape(x.label||'Suplemento')}</span><span>${euro(x.amount)}</span></div>`).join('')}${t.rate!==null?`<div class="paper-row paper-muted"><span>Base imponible</span><span>${euro(t.base)}</span></div><div class="paper-row paper-muted"><span>IVA (${t.rate} %, incluido)</span><span>${euro(t.tax)}</span></div>`:''}</div><div class="paper-total"><span>Total</span><strong>${euro(t.total)}</strong></div>${s.notes?'<p class="paper-muted">'+escape(s.notes)+'</p>':''}${issued?'<p class="paper-muted">Emitido el '+escape(new Date(issued.created).toLocaleDateString('es-ES'))+'</p>':''}<div class="paper-thanks">Gracias por viajar con nosotros.</div>`;}
async function api(path,options={}){return localAPI(path,options);}

async function sync(){try{const data=await api('state');onlineReady=true;const previousUser=userKey;userKey=data.user;localSet('taxi-last-user',userKey);if(!dirtyCompany){savedCompany=data.company;company={...companyDefaults,...(data.company||{})};revision=data.revision;fill(companyForm,company);$('#company-status').textContent=data.company?'Datos guardados en este dispositivo.':'Completa y guarda los datos de tu empresa.';}if(previousUser!==userKey){issued=null;pendingIssue=null;service=freshService();const draft=localGet(draftKey())||localGet('taxi-draft-v1:offline');if(draft?.service){service=draft.service;pendingIssue=draft.pendingIssue||null;}fill(form,service);renderSupplements();}$('#sync-status').textContent=navigator.onLine?'Guardado en este dispositivo':'Sin conexión · guardado en este dispositivo';render();}catch(e){onlineReady=false;$('#sync-status').textContent='No se puede acceder al almacenamiento del navegador';}}
companyForm.onsubmit=async e=>{e.preventDefault();if(busy)return;let data;try{data=validateCompany(collect(companyForm));}catch(e){toast(e.message);return;}$('#save-company').disabled=true;try{const result=await api('company',{method:'PUT',body:JSON.stringify({company:data,revision})});company=result.company;savedCompany=result.company;revision=result.revision;dirtyCompany=false;$('#company-status').textContent='Datos guardados en este dispositivo.';toast('Datos de empresa guardados.');render();}catch(e){toast(e.message);$('#company-status').textContent=e.message;if(e.status===409){const state=await api('state').catch(()=>null);if(state)revision=state.revision;$('#company-status').textContent='Los datos cambiaron en otra pestaña. Revisa tu formulario y pulsa Guardar para aplicar esta versión.';}}finally{$('#save-company').disabled=false;}};
async function issue(){if(issued){newService();return;}if(busy)return;if(!pendingIssue){if(dirtyCompany||!savedCompany){setTab('company');toast('Guarda los datos de tu empresa antes de emitir.');return;}try{validateService(service,savedCompany);}catch(e){setTab('service');toast(e.message);return;}pendingIssue={id:crypto.randomUUID(),service:structuredClone(service),revision};saveDraft();}busy=true;render();try{const result=await api('documents',{method:'POST',body:JSON.stringify(pendingIssue)});issued=result.document;pendingIssue=null;service=issued.data.service;localSet(draftKey(),null);toast(`${docNumber(issued)} emitido. Ya puedes descargarlo o compartirlo.`);$('#sync-status').textContent='Documento guardado en este dispositivo';}catch(e){if(e.status&&e.status>=400){pendingIssue=null;saveDraft();if(e.status===409){await sync();toast('Los datos de la empresa han cambiado. Revisa la vista previa y vuelve a emitir.');}else toast(e.message);}else{saveDraft();toast('No pudimos confirmar el guardado. Pulsa «Reintentar emisión» para recuperar el mismo documento sin duplicarlo.');}}finally{busy=false;render();}}
$('#issue').onclick=issue;
function newService(){if(pendingIssue){toast('Confirma primero la emisión pendiente para evitar duplicados.');return;}if(!issued&&(service.origin||service.destination||service.fare||service.clientName)&&!confirm('¿Empezar otro servicio? Se descartará este borrador sin emitir.'))return;issued=null;service=freshService();fill(form,service);renderSupplements();saveDraft();render();setTab('service');window.scrollTo({top:0,behavior:'smooth'});sync();}
$('#new-service').onclick=newService;
function documentText(){const {company:p,service:s}=issued.data,t=totals(s);return [p.title,`Licencia: ${p.license}`,`Matrícula: ${p.plate}`,'',p.name,`NIF/CIF: ${p.nif}`,p.address,p.nick,p.phone,p.email,'',`${s.kind==='invoice'?'FACTURA':'RECIBO'} ${docNumber(issued)}`,'',`Fecha del servicio: ${displayDate(s.date)} ${s.time}`,`Fecha de emisión: ${new Date(issued.created).toLocaleDateString('es-ES')}`,`Forma de pago: ${s.payment}`,'',...(s.clientName||s.clientNif||s.clientAddress?['CLIENTE',s.clientName,s.clientNif?'NIF/CIF: '+s.clientNif:'',s.clientAddress,'']:[]),`Origen: ${s.origin}`,`Destino: ${s.destination}`,'',`Trayecto: ${euro(t.fare)}`,...t.supplements.map(x=>`${x.label}: ${euro(x.amount)}`),...(t.rate!==null?[`Base imponible: ${euro(t.base)}`,`IVA (${t.rate} %, incluido): ${euro(t.tax)}`]:[]),`TOTAL: ${euro(t.total)}`,'',s.notes,'Gracias por viajar con nosotros.'].filter(x=>x!==undefined).join('\n');}
function saveFile(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);}
function exportFilename(extension){return `servicio-taxi-${issued.data.service.date}-${docNumber(issued)}.${extension}`;}
function download(blob,extension){saveFile(blob,exportFilename(extension));}
function pdfBlob(){if(!window.jspdf)throw new Error('No se pudo cargar el generador PDF. Puedes usar Imprimir o descargar el texto.');const pdf=new window.jspdf.jsPDF({unit:'mm',format:'a4'});const {company:p,service:s}=issued.data,t=totals(s);let y=26;function line(text,size=10,bold=false,color=[40,43,47]){pdf.setFont('helvetica',bold?'bold':'normal');pdf.setFontSize(size);pdf.setTextColor(...color);for(const row of pdf.splitTextToSize(String(text||''),170)){if(y>272){pdf.addPage();y=23;}pdf.text(row,20,y);y+=size*.44+1;} }function space(n=5){y+=n;}pdf.setFillColor(245,200,66);pdf.rect(20,15,170,2,'F');line(p.title,19,true);line(`Licencia nº ${p.license}`,11);line(`Matrícula ${p.plate}`,11);space();line(p.name,12,true);line(`NIF/CIF: ${p.nif}`);for(const v of [p.address,p.nick,p.phone,p.email])if(v)line(v);space();line(`${s.kind==='invoice'?'FACTURA':'RECIBO'}  ${docNumber(issued)}`,12,true);space(2);line(`Fecha del servicio: ${displayDate(s.date)}   ${s.time}`);line(`Fecha de emisión: ${new Date(issued.created).toLocaleDateString('es-ES')}`);line(`Forma de pago: ${s.payment}`);space();if(s.clientName||s.clientNif||s.clientAddress){line('CLIENTE',10,true);if(s.clientName)line(s.clientName);if(s.clientNif)line('NIF/CIF: '+s.clientNif);if(s.clientAddress)line(s.clientAddress);space();}line('ORIGEN',9,true);line(s.origin,11);space(2);line('DESTINO',9,true);line(s.destination,11);space();line('DESGLOSE',9,true);line(`Servicio de taxi: ${euro(t.fare)}`);for(const x of t.supplements)line(`${x.label}: ${euro(x.amount)}`);if(t.rate!==null){space(2);line(`Base imponible: ${euro(t.base)}`);line(`IVA (${t.rate} %, incluido): ${euro(t.tax)}`);}space();line(`TOTAL  ${euro(t.total)}`,19,true);space();if(s.notes){line('OBSERVACIONES',9,true);line(s.notes);space();}line('Gracias por viajar con nosotros.',10,false,[110,115,122]);for(let i=1;i<=pdf.getNumberOfPages();i++){pdf.setPage(i);pdf.setFontSize(8);pdf.setTextColor(120);pdf.text(`${docNumber(issued)} · ${i} / ${pdf.getNumberOfPages()}`,20,286);}return pdf.output('blob');}
$('#pdf').onclick=()=>{try{download(pdfBlob(),'pdf');}catch(e){toast(e.message);}};$('#text').onclick=()=>download(new Blob(['\ufeff'+documentText()],{type:'text/plain;charset=utf-8'}),'txt');$('#print').onclick=()=>{document.title=exportFilename('pdf').replace(/\.pdf$/,'');window.print();document.title='Taxi · Recibos';};
$('#share').onclick=async()=>{try{const file=new File([pdfBlob()],exportFilename('pdf'),{type:'application/pdf'});if(navigator.canShare?.({files:[file]})){await navigator.share({files:[file],title:docNumber(issued)});}else if(navigator.share){await navigator.share({title:docNumber(issued),text:documentText()});}else{download(file,'pdf');toast('PDF descargado. Puedes adjuntarlo por WhatsApp o email.');}}catch(e){if(e.name!=='AbortError')toast(e.message||'No se pudo compartir. Descarga el PDF para adjuntarlo.');}};
async function showHistory(reset=true){const list=$('#history-list');if(reset){historyOffset=0;list.innerHTML='<p class="empty-state">Cargando documentos…</p>';if(!$('#history-dialog').open)$('#history-dialog').showModal();}try{const data=await api('documents?offset='+historyOffset);if(reset)list.innerHTML='';list.querySelector('.load-more')?.remove();if(!data.documents.length&&!historyOffset)list.innerHTML='<p class="empty-state">Todavía no hay documentos.<br>Tu primer recibo aparecerá aquí al emitirlo.</p>';for(const d of data.documents){const b=document.createElement('button');b.className='history-row';b.innerHTML=`<span><strong>${escape(docNumber(d))}</strong><small>${displayDate(d.data.service.date)} · ${escape(d.data.service.clientName||d.data.service.destination)}</small></span><strong>${euro(totals(d.data.service).total)}</strong>`;b.onclick=()=>{if(pendingIssue){toast('Confirma primero la emisión pendiente.');return;}if(!issued&&(service.origin||service.destination||service.fare)&&!confirm('¿Abrir este documento? Se conservará tu borrador para cuando vuelvas a abrir la app.'))return;issued=d;service=d.data.service;fill(form,service);renderSupplements();render();setTab('service');$('#history-dialog').close();$('.preview-column').scrollIntoView({behavior:'smooth',block:'start'});};list.append(b);}historyOffset+=data.documents.length;if(data.more){const more=document.createElement('button');more.className='button quiet load-more';more.textContent='Cargar más';more.onclick=()=>showHistory(false);list.append(more);}}catch(e){if(reset)list.innerHTML='';const p=document.createElement('p');p.className='empty-state';p.textContent=e.message;list.append(p);const retry=document.createElement('button');retry.className='button quiet';retry.textContent='Reintentar';retry.onclick=()=>showHistory(true);list.append(retry);}}
$('#history-button').onclick=()=>showHistory();$$('[data-close]').forEach(b=>b.onclick=()=>$('#'+b.dataset.close).close());
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;});$('#install').onclick=async()=>{if(installPrompt){await installPrompt.prompt();installPrompt=null;}else $('#install-dialog').showModal();};window.addEventListener('appinstalled',()=>{$('#install').hidden=true;toast('Aplicación instalada.');});if(matchMedia('(display-mode: standalone)').matches)$('#install').textContent='Instalación / ayuda';
userKey='this-device';const draft=localGet(draftKey());if(draft?.service&&Array.isArray(draft.service.supplements)){service={...freshService(),...draft.service};pendingIssue=draft.pendingIssue||null;}fill(form,service);fill(companyForm,company);renderSupplements();render();sync();window.addEventListener('online',sync);window.addEventListener('offline',()=>{$('#sync-status').textContent='Sin conexión · guardado en este dispositivo';onlineReady=false;});document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&!busy)sync();});
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js',{scope:'./',updateViaCache:'none'}).catch(()=>{ $('#sync-status').textContent='El modo sin conexión no está disponible en este navegador.'; });
if(document.modelContext?.registerTool){const controller=new AbortController();try{Promise.resolve(document.modelContext.registerTool({name:'read_taxi_document_draft',title:'Consultar el servicio de taxi',description:'Lee el borrador visible o el documento emitido, sin emitir ni modificar datos.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:input=>{if(!input||Object.keys(input).length)throw new Error('No se admiten parámetros.');return {status:issued?'issued':pendingIssue?'pending':'draft',number:issued?docNumber(issued):null,service:structuredClone(service)};}},{signal:controller.signal})).catch(()=>{});}catch{}window.addEventListener('pagehide',()=>controller.abort(),{once:true});}

$('#backup-export').onclick=async()=>{try{const data=await api('backup');saveFile(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),'taxi-copia-'+new Date().toISOString().slice(0,10)+'.json');$('#backup-status').textContent='Copia descargada: '+data.documents.length+' documentos. Guarda el archivo fuera de este navegador.';toast('Copia JSON descargada. Incluye documentos, empresa y contador.');}catch(e){toast(e.message);}};
$('#backup-import').onclick=()=>$('#backup-file').click();
$('#backup-file').onchange=async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;if(pendingIssue){toast('Confirma primero la emisión pendiente.');return;}try{if(file.size>20*1024*1024)throw new Error('La copia es demasiado grande. Máximo 20 MB.');const text=await file.text();let data;try{data=JSON.parse(text.replace(/^\uFEFF/,''));}catch{throw new Error('El archivo no contiene un JSON válido.');}const checked=validateBackup(data);if(!confirm('¿Importar '+checked.documents.length+' documentos de '+(checked.company?.name||'esta copia')+'? Se conservarán los existentes. Si hay números en conflicto, no se importará nada.'))return;const result=await api('backup',{method:'POST',body:JSON.stringify(data)});dirtyCompany=false;await sync();await showHistory();$('#backup-status').textContent=result.imported+' documentos importados · '+result.skipped+' ya estaban guardados.';toast('Copia importada. El contador se ha actualizado.');}catch(e){toast(e.message);$('#backup-status').textContent=e.message;}};
if(navigator.storage?.persist)navigator.storage.persist().catch(()=>{});
