export const companyDefaults={title:'Servicio taxi APC Granada',name:'',nif:'',license:'',plate:'',address:'',nick:'',phone:'',email:''};
export function freshService(){const d=new Date(),local=new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString();return {kind:'receipt',date:local.slice(0,10),time:local.slice(11,16),origin:'',destination:'',clientName:'',clientNif:'',clientAddress:'',fare:'',payment:'Efectivo',vat:'10',notes:'',supplements:[]};}
export function cents(value){const s=String(value??'').trim().replace(',','.');if(!/^\d{1,6}(\.\d{1,2})?$/.test(s))throw new Error('Introduce un importe válido con un máximo de dos decimales.');const [whole,part='']=s.split('.');return Number(whole)*100+Number(part.padEnd(2,'0'));}
export function supplementCents(s){if(s.type==='luggage'){if(!Number.isInteger(s.quantity)||s.quantity<1||s.quantity>5)throw new Error('Elige entre 1 y 5 maletas o bultos.');return cents(s.unitAmount||'0')*s.quantity;}return cents(s.amount||'0');}
export function totals(service){const total=cents(service.fare||'0'),supplements=(service.supplements||[]).map(s=>({label:s.type==='luggage'?`Maletas o bultos (${s.quantity} × ${euro(cents(s.unitAmount||'0'))})`:s.label,amount:supplementCents(s)}));const extras=supplements.reduce((sum,s)=>sum+s.amount,0),fare=total-extras;if(fare<0)throw new Error('Los suplementos incluidos no pueden superar el importe total del servicio.');if(total>99999999)throw new Error('El importe total es demasiado alto.');const rate=service.vat===''?null:Number(service.vat),base=rate===null?total:Math.round(total*100/(100+rate));return {fare,supplements,total,base,tax:total-base,rate};}
export const euro=c=>new Intl.NumberFormat('es-ES',{style:'currency',currency:'EUR'}).format(c/100);
export const displayDate=s=>/^\d{4}-\d{2}-\d{2}$/.test(s)?s.split('-').reverse().join('/'):'—';
export const documentKinds=['invoice','receipt','invoice-correction','receipt-correction'];
export const docNumber=d=>`${({'invoice':'F','receipt':'R','invoice-correction':'FR','receipt-correction':'RC'})[d.kind]}-${d.year}-${String(d.seq).padStart(4,'0')}`;
export const docTitle=d=>d.kind==='invoice-correction'?'Factura rectificativa':d.kind==='receipt-correction'?'Recibo corregido':d.kind==='invoice'?'Factura':'Recibo';
export function correctionData(source,reason){reason=clean(reason,240,'motivo de la corrección',true);return{sourceId:source.id,reference:docNumber(source),sourceCreated:source.created,reason,method:'replacement',oldBase:source.data.amounts.base,oldTax:source.data.amounts.tax,oldTotal:source.data.amounts.total};}
export function normalizeSupplement(item){if(!item||typeof item!=='object')throw new Error('Revisa el suplemento.');if(item.type==='luggage'){const unitAmount=clean(item.unitAmount,12,'precio por maleta o bulto',true),quantity=item.quantity;if(!Number.isInteger(quantity)||quantity<1||quantity>5)throw new Error('Elige entre 1 y 5 maletas o bultos.');const amount=(cents(unitAmount)*quantity/100).toFixed(2);return{type:'luggage',label:'Maletas o bultos',quantity,unitAmount,amount};}if(item.type==='station')return{type:'station',label:'Salida de estación',amount:clean(item.amount,12,'suplemento por salida de estación',true)};if(item.type!==undefined)throw new Error('El tipo de suplemento no es válido.');return{label:clean(item.label,100,'concepto del suplemento',true),amount:clean(item.amount,12,'importe del suplemento',true)};}
function clean(v,max,name,required=false){if(typeof v!=='string'||v.length>max||/[\u0000-\u0008\u000B\u000C\u000E-\u001F]/.test(v))throw new Error('Revisa el campo '+name+'.');const s=v.trim();if(required&&!s)throw new Error('Completa '+name+'.');return s;}
export function validateCompany(p){if(!p||typeof p!=='object')throw new Error('Completa los datos de tu empresa.');const result={};for(const [k,len,label,req] of [['title',100,'título',true],['name',160,'titular',true],['nif',30,'NIF/CIF del titular',true],['license',40,'número de licencia',true],['plate',20,'matrícula',true],['address',240,'dirección fiscal'],['nick',60,'nick'],['phone',30,'teléfono'],['email',160,'email']])result[k]=clean(p[k]??'',len,label,req);if(result.email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(result.email))throw new Error('Revisa el email de tu empresa.');return result;}
export function validateService(s,p){p=validateCompany(p);if(!s||!['receipt','invoice'].includes(s.kind))throw new Error('Elige recibo o factura.');const invoice=s.kind==='invoice';const v={kind:s.kind};for(const [k,max,label,req] of [['date',10,'fecha',true],['time',5,'hora',true],['origin',180,'origen',true],['destination',180,'destino',true],['clientName',160,'nombre del cliente',invoice],['clientNif',30,'NIF/CIF del cliente',invoice],['clientAddress',240,'dirección fiscal del cliente',invoice],['notes',500,'observaciones'],['fare',12,'importe del trayecto',true]])v[k]=clean(s[k]??'',max,label,req);if(!/^\d{4}-\d{2}-\d{2}$/.test(v.date)||Number(v.date.slice(0,4))<2000||Number(v.date.slice(0,4))>2100||Number.isNaN(Date.parse(v.date))||new Date(v.date).toISOString().slice(0,10)!==v.date)throw new Error('Revisa la fecha del servicio.');if(!/^([01]\d|2[0-3]):[0-5]\d$/.test(v.time))throw new Error('Revisa la hora del servicio.');if(!['','10'].includes(s.vat)||invoice&&s.vat==='')throw new Error('Selecciona el IVA para la factura.');v.vat=s.vat;if(invoice&&!p.address)throw new Error('Completa la dirección fiscal de tu empresa.');if(!['Efectivo','Tarjeta'].includes(s.payment))throw new Error('Selecciona una forma de pago.');v.payment=s.payment;if(!Array.isArray(s.supplements)||s.supplements.length>12)throw new Error('Puedes añadir hasta 12 suplementos.');v.supplements=s.supplements.map(normalizeSupplement);const typed=v.supplements.filter(x=>x.type).map(x=>x.type);if(new Set(typed).size!==typed.length)throw new Error('Cada tipo de suplemento se puede incluir una sola vez.');const amounts=totals(v);if(amounts.total<=0)throw new Error('El importe total debe ser mayor que cero.');return {company:p,service:v,amounts};}
