import {validateCompany,validateService} from './core.js';import {validateBackup,mergeBackup} from './backup.js';
let dbPromise;function open(){if(!dbPromise)dbPromise=new Promise((resolve,reject)=>{const r=indexedDB.open('taxi-apc-granada-v1:'+new URL('.',import.meta.url).pathname,1);r.onupgradeneeded=()=>{const db=r.result;db.createObjectStore('settings');const docs=db.createObjectStore('documents',{keyPath:'id'});docs.createIndex('number',['kind','year','seq'],{unique:true});db.createObjectStore('counters',{keyPath:['kind','year']});};r.onsuccess=()=>{r.result.onversionchange=()=>r.result.close();resolve(r.result);};r.onerror=()=>reject(new Error('No se puede abrir el almacenamiento. Prueba un navegador normal, fuera del modo privado.'));r.onblocked=()=>reject(new Error('Cierra las otras pestañas de esta aplicación y vuelve a abrirla.'));});return dbPromise;}
const req=r=>new Promise((resolve,reject)=>{r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});
async function transaction(mode,action){const db=await open(),tx=db.transaction(['settings','documents','counters'],mode);const done=new Promise((resolve,reject)=>{tx.oncomplete=resolve;tx.onabort=()=>reject(tx.error||new Error('No se han guardado los cambios.'));tx.onerror=()=>{};});try{const result=await action(tx.objectStore('settings'),tx.objectStore('documents'),tx.objectStore('counters'));await done;return result;}catch(e){try{tx.abort();}catch{}await done.catch(()=>{});throw e;}}
function fail(message,status=400){const e=new Error(message);e.status=status;throw e;}
export async function localAPI(path,options={}){const method=options.method||'GET',body=options.body?JSON.parse(options.body):null,url=new URL(path,'https://local.test/');try{
if(path==='state')return await transaction('readonly',async settings=>{const p=await req(settings.get('profile'));return{user:'this-device',company:p?.company||null,revision:p?.revision||0};});
if(path==='company'&&method==='PUT'){const company=validateCompany(body.company);return await transaction('readwrite',async settings=>{const old=await req(settings.get('profile'));if((old?.revision||0)!==body.revision)fail('Los datos cambiaron en otra pestaña. Revísalos antes de guardar.',409);const result={company,revision:(old?.revision||0)+1};await req(settings.put(result,'profile'));return result;});}
if(url.pathname==='/documents'&&method==='GET')return await transaction('readonly',async(s,docs)=>{const all=await req(docs.getAll());all.sort((a,b)=>b.created.localeCompare(a.created)||b.id.localeCompare(a.id));const offset=Number(url.searchParams.get('offset')||0);return{documents:all.slice(offset,offset+30),more:all.length>offset+30};});
if(path==='documents'&&method==='POST')return await transaction('readwrite',async(settings,docs,counters)=>{const existing=await req(docs.get(body.id));if(existing)return{document:existing};const profile=await req(settings.get('profile'));if(!profile)fail('Guarda los datos del titular antes de emitir.');if(profile.revision!==body.revision)fail('Los datos de empresa han cambiado. Revísalos antes de emitir.',409);let data;try{data=validateService(body.service,profile.company);}catch(e){fail(e.message);}const kind=data.service.kind,year=Number(data.service.date.slice(0,4));const counter=await req(counters.get([kind,year]));const seq=counter?.next||1;if(seq>99999999)fail('Se ha alcanzado el límite de esta serie.');const document={id:body.id,kind,year,seq,created:new Date().toISOString(),data};await req(docs.add(document));await req(counters.put({kind,year,next:seq+1}));return{document};});
if(path==='backup'&&method==='GET')return await transaction('readonly',async(settings,docs,counters)=>({format:'taxi-apc-granada',version:1,exportedAt:new Date().toISOString(),company:(await req(settings.get('profile')))?.company||null,documents:await req(docs.getAll()),counters:await req(counters.getAll())}));
if(path==='backup'&&method==='POST'){const backup=validateBackup(body);return await transaction('readwrite',async(settings,docs,counters)=>{const profile=await req(settings.get('profile'));const merged=mergeBackup({company:profile?.company||null,documents:await req(docs.getAll()),counters:await req(counters.getAll())},backup);for(const d of merged.documents)await req(docs.add(d));for(const c of merged.counters)await req(counters.put(c));if(!profile&&merged.company)await req(settings.put({company:merged.company,revision:1},'profile'));return{imported:merged.imported,skipped:merged.skipped};});}
fail('Operación desconocida.');
}catch(e){if(e.name==='QuotaExceededError')fail('No queda espacio en el dispositivo. Libera espacio y vuelve a intentarlo; no se ha emitido el documento.',507);throw e;}}
